create table project_settings (
    id bigint primary key,
    project_name varchar(255) not null,
    project_start_date date not null,
    project_end_date date not null,
    exclude_non_working_days boolean not null,
    version integer not null
);

create table members (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    name varchar(255) not null,
    display_order integer not null
);

create table tasks (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    name varchar(255) not null,
    owner varchar(255) not null,
    start_date date not null,
    end_date date not null,
    progress integer not null,
    status varchar(32) not null,
    parent_task_id bigint,
    task_type varchar(32) not null,
    display_order integer not null
);

create table dependencies (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    from_task_id bigint not null,
    to_task_id bigint not null
);

create table holidays (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    date date not null,
    name varchar(255) not null,
    constraint uq_holidays_project_date unique (project_id, date)
);

create table project_versions (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    version integer not null,
    saved_at timestamp not null,
    snapshot_json clob not null,
    note varchar(255),
    constraint uq_project_versions_project_version unique (project_id, version)
);
