create table tasks (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    owner varchar(255) not null,
    start_date date not null,
    end_date date not null,
    progress integer not null,
    status varchar(32) not null
);

create table dependencies (
    id bigint generated by default as identity primary key,
    from_task_id bigint not null,
    to_task_id bigint not null
);

insert into tasks (name, owner, start_date, end_date, progress, status) values
('要件整理', 'Mina', '2026-05-01', '2026-05-04', 100, 'DONE'),
('画面設計', 'Ren', '2026-05-03', '2026-05-08', 72, 'IN_PROGRESS'),
('API 実装', 'Kai', '2026-05-06', '2026-05-13', 48, 'IN_PROGRESS'),
('フロント実装', 'Aoi', '2026-05-07', '2026-05-15', 36, 'IN_PROGRESS'),
('受け入れテスト', 'Sora', '2026-05-16', '2026-05-20', 0, 'TODO');

insert into dependencies (from_task_id, to_task_id) values
(1, 2),
(2, 3),
(2, 4),
(3, 5),
(4, 5);
