alter table tasks add column parent_task_id bigint;
alter table tasks add column task_type varchar(32) not null default 'TASK';
alter table tasks add column display_order integer not null default 0;

update tasks set display_order = id - 1;

create table members (
    id bigint generated by default as identity primary key,
    name varchar(255) not null,
    display_order integer not null
);

create table project_settings (
    id bigint primary key,
    project_name varchar(255) not null,
    project_start_date date not null,
    project_end_date date not null,
    exclude_non_working_days boolean not null
);

insert into members (name, display_order) values
('Mina', 0),
('Ren', 1),
('Kai', 2),
('Aoi', 3),
('Sora', 4);

insert into project_settings (id, project_name, project_start_date, project_end_date, exclude_non_working_days) values
(1, 'チーム進行ガントチャート', '2026-05-01', '2026-05-20', false);
