create table if not exists project_versions (
    id bigint generated by default as identity primary key,
    version integer not null unique,
    saved_at timestamp not null,
    snapshot_json clob not null
);
