alter table tasks add column if not exists project_id bigint;
update tasks set project_id = 1 where project_id is null;
alter table tasks alter column project_id set not null;

alter table dependencies add column if not exists project_id bigint;
update dependencies set project_id = 1 where project_id is null;
alter table dependencies alter column project_id set not null;

alter table members add column if not exists project_id bigint;
update members set project_id = 1 where project_id is null;
alter table members alter column project_id set not null;

create table holidays_new (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    date date not null,
    name varchar(255) not null
);

insert into holidays_new (id, project_id, date, name)
select id, 1, date, name
from holidays;

drop table holidays;
alter table holidays_new rename to holidays;
alter table holidays add constraint uq_holidays_project_date unique (project_id, date);

create table project_versions_new (
    id bigint generated by default as identity primary key,
    project_id bigint not null,
    version integer not null,
    saved_at timestamp not null,
    snapshot_json clob not null,
    note varchar(255)
);

insert into project_versions_new (id, project_id, version, saved_at, snapshot_json, note)
select id, 1, version, saved_at, snapshot_json, note
from project_versions;

drop table project_versions;
alter table project_versions_new rename to project_versions;
alter table project_versions add constraint uq_project_versions_project_version unique (project_id, version);
